#!/usr/bin/env bash
# bootstrap-worktree.sh — make a fresh git worktree runnable for this project.
#
# The dispatcher runs this after every `git worktree add`. A bare worktree has
# tracked files only: no dependencies, no secrets, no generated code — and no
# tier-1 skill symlinks (gitignored symlinks never materialize in new
# worktrees). This script closes that gap. It must be IDEMPOTENT (it re-runs on
# worktree re-attach) and NON-INTERACTIVE (it runs unattended inside the loop).
#
# Usage: scripts/bootstrap-worktree.sh <target-worktree-path>
set -euo pipefail
WT="${1:?usage: bootstrap-worktree.sh <target-worktree-path>}"

# --- context-specs deterministic section (do not edit or remove) -------------
# Re-create the tier-1 skill/agent symlinks in the new worktree so headless
# skills resolve there. The `context-specs` CLI is installed globally (npm), and
# CONTEXT_SPECS_HOME tells it WHICH harness to link from — the dispatcher
# exports it; a human running this by hand exports their harness repo path.
# Idempotent and fast.
: "${CONTEXT_SPECS_HOME:?export CONTEXT_SPECS_HOME=<path to your harness repo>, or invoke via the harness}"
context-specs link "$WT"
# --- project-specific provisioning below (generated by /env-init) ------------

# The developer's real clone — where the real gitignored secrets live. Derived
# from the worktree's shared git dir, so this works regardless of where the
# worktree happens to be checked out.
SRC="$(dirname "$(git -C "$WT" rev-parse --git-common-dir)")"

# 1. Copy gitignored secrets, source checkout -> worktree only. Never the
#    reverse, never deleted (Invariant 6) — this is the harness's one
#    touchpoint for sensitive files. Both are gitignored (backend/.env,
#    frontend/.env in .gitignore) and named by their .env.example siblings
#    (ODDS_API_KEY, ALLOWED_ORIGINS, ... / VITE_API_URL). Copy only what
#    exists in the source; an optional/missing one is not a failure.
for envfile in backend/.env frontend/.env; do
  if [[ -f "$SRC/$envfile" ]]; then
    cp "$SRC/$envfile" "$WT/$envfile"
    echo "bootstrap: copied $envfile from $SRC"
  else
    echo "bootstrap: $SRC/$envfile not found, skipping (feature may be limited to what doesn't need it)"
  fi
done

# 2. Backend deps — fresh venv per worktree (venv/ is gitignored and often
#    embeds absolute paths, so it is never copied, only rebuilt). Guarded on a
#    hash of requirements.txt so a re-run without a dependency change is a
#    cheap no-op.
REQS="$WT/backend/requirements.txt"
VENV="$WT/backend/venv"
STAMP="$VENV/.requirements.sha256"
NEW_HASH="$(shasum -a 256 "$REQS" | awk '{print $1}')"
if [[ ! -f "$STAMP" ]] || [[ "$(cat "$STAMP")" != "$NEW_HASH" ]]; then
  echo "bootstrap: installing backend dependencies"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet -r "$REQS"
  echo "$NEW_HASH" > "$STAMP"
else
  echo "bootstrap: backend venv up to date, skipping install"
fi

# 3. Frontend deps — npm ci needs the committed lockfile (frontend/package-lock.json).
#    Guarded on node_modules already present + lockfile unchanged since last install.
LOCKFILE="$WT/frontend/package-lock.json"
NODE_MODULES="$WT/frontend/node_modules"
FRONTEND_STAMP="$NODE_MODULES/.package-lock.sha256"
if [[ -f "$LOCKFILE" ]]; then
  NEW_LOCK_HASH="$(shasum -a 256 "$LOCKFILE" | awk '{print $1}')"
  if [[ ! -d "$NODE_MODULES" ]] || [[ ! -f "$FRONTEND_STAMP" ]] || [[ "$(cat "$FRONTEND_STAMP")" != "$NEW_LOCK_HASH" ]]; then
    echo "bootstrap: installing frontend dependencies"
    ( cd "$WT/frontend" && npm ci --silent )
    echo "$NEW_LOCK_HASH" > "$FRONTEND_STAMP"
  else
    echo "bootstrap: frontend node_modules up to date, skipping install"
  fi
else
  echo "bootstrap: frontend/package-lock.json missing — cannot run npm ci" >&2
  exit 1
fi

# No codegen step: no Prisma/protobuf/GraphQL codegen or migrations detected
# in this project.
